<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22908" started-at="2019-06-01T11:19:01Z" finished-at="2019-06-01T11:19:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22908" started-at="2019-06-01T11:19:01Z" finished-at="2019-06-01T11:19:24Z">
      <class name="com.MS.qa.testcases.ProductTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.MS.qa.testcases.ProductTest@1a968a59]" name="setUp" is-config="true" duration-ms="22125" started-at="2019-06-01T16:49:01Z" finished-at="2019-06-01T16:49:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkOutProduct()[pri:0, instance:com.MS.qa.testcases.ProductTest@1a968a59]" name="checkOutProduct" duration-ms="10" started-at="2019-06-01T16:49:23Z" finished-at="2019-06-01T16:49:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.MS.qa.pages.ProductPage.checkOutProduct(ProductPage.java:30)
	at com.MS.qa.testcases.ProductTest.checkOutProduct(ProductTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOutProduct -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.MS.qa.testcases.ProductTest@1a968a59]" name="tearDown" is-config="true" duration-ms="748" started-at="2019-06-01T16:49:23Z" finished-at="2019-06-01T16:49:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.MS.qa.testcases.ProductTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
